### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by herpiko** [BlankOn/irgsh-node#4]

**Comment by herpiko** [comment]
# Langkah reka ulang untuk Dockerfile

## Basis citra

Pull dari debian:stable-slim (jessie)

## Persiapan sistem 
```
$ apt-get update
$ apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils sudo python python-pip python-dev python-debian dpkg-dev rabbitmq-server git-core nginx libpq-dev dput pbuilder git-core python-lzma python-chardet git vim
```

Tambah user `irgsh`, izinkan sudo, masuk sebagai user tersebut.

## Pasang pyenv / python 2.6.6

Pasang pakai `https://github.com/pyenv/pyenv-installer`

```
$ pyenv install 2.6.6
$ pyenv shell 2.6.6
```

Selanjutnya di dalam `2.6.6`

## Kloning repositori
```
$ mkdir src
$ cd src
$ git clone git://github.com/BlankOn/python-irgsh.git
$ git clone git://github.com/BlankOn/irgsh-node.git
$ cd irgsh-node
$ ln -s ../python-irgsh/irgsh
```
## Bangun

```
$ python bootstrap.py
```

### Workaround untuk pyparsing
```
$ pip uninstall pyparsing
$ rm -rf eggs/pyparsing*`
```

Sunting baris 59 dari  `/home/irgsh/.pyenv/versions/2.6.6/lib/python2.6/site-packages/packaging/requirements.py`

Dari `MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")` ke `MARKER_EXPR = originalTextFor(MARKER_EXPR)("marker")`.


Lalu `pip install pyparsing==1.5.7`, ulangi 2 kali (sampai berhasil)

### Buildout 
```
./bin/buildout
```

**Comment by showcheap** [comment]
Galat:
```
root@adeb31b4354a:~/src/irgsh-web# ./bin/buildout 
/root/.pyenv/versions/2.6.6/lib/python2.6/site-packages/pkg_resources/__init__.py:213: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Getting distribution for 'setuptools'.
warning: no files found matching '*' under directory 'setuptools/_vendor'
Got setuptools 34.3.2.
Upgraded:
  setuptools version 34.3.2;
restarting.
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "./bin/buildout", line 15, in <module>
    import site # imports custom buildout-generated site.py
  File "/root/src/irgsh-web/parts/buildout/site.py", line 552, in <module>
    main()
  File "/root/src/irgsh-web/parts/buildout/site.py", line 535, in main
    known_paths = addsitepackages(known_paths)
  File "/root/src/irgsh-web/parts/buildout/site.py", line 262, in addsitepackages
    import pkg_resources
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 48, in <module>
ImportError: No module named six
```

**Comment by herpiko** [comment]
@showcheap Coba,

```
pip install --ignore-installed six
```

**Comment by herpiko** [comment]
Atau,
```
pip install --upgrade --ignore-installed six
```

**Comment by suciptoid** [comment]
Eh maap pak tadi galat di repo sebelah (irgsh-web)

**Comment by i5um41ru** [comment]
[irgsh-node.json.zip](https://github.com/BlankOn/irgsh-node/files/876430/irgsh-node.json.zip)
ini berkas asciinema saya, mohon di cek dulu.

**Comment by herpiko** [comment]
Done by @showcheap https://github.com/showcheap/irgsh-node-docker

Thanks.

**Comment by herpiko** [comment]
Please move the dockerfile to this repo
